menu: #菜单导航
  home: /
  archives: /archives
  categories: /categories
  tags: /tags
  #friends: /friends
  about: /about

logo: /images/logo.png #logo图片

categories_max: 5 #categories-max 分类最大数量
 
tags_max: 10 #tags-max 标签最大数量

favicon: /images/favicon.ico #favicon 网站favicon(浏览器左上角小图标)

site_search: true #site switch 

rss: /atom.xml #rss 订阅标签

follow: #follow 其他站点 按顺序展示
  github: 'https://github.com/ddddderek'
  zhihu: ''
  QQ: ''

search_url: /search.xml #search post url

site_icp: '' #ICP 网站备案

share: #分享平台
  - weibo
  - weixin
  - qqkongjian

#cdn 加速
cdn_script: #script
  css: 'https://cdn.bootcss.com/require-css/0.1.10/css.min.js'
  pjax: 'https://cdn.bootcss.com/jquery.pjax/2.0.1/jquery.pjax.min.js'
  av_min: 'https://cdn.jsdelivr.net/npm/leancloud-storage/dist/av-min.js'
  jquery: 'https://cdn.bootcss.com/jquery/3.4.1/jquery.min.js'
  require: 'https://cdn.bootcss.com/require.js/2.3.6/require.min.js'
  confirm: 'https://cdn.bootcss.com/jquery-confirm/3.3.4/jquery-confirm.min.js'
  fancybox: 'https://cdn.bootcss.com/fancybox/3.5.7/jquery.fancybox.min.js'
  chart: 'https://cdn.bootcss.com/Chart.js/2.8.0-rc.1/Chart.bundle.min.js'

cdn_css: #css
  confirm: 'https://cdn.bootcss.com/jquery-confirm/3.3.4/jquery-confirm.min.css'
  fancybox: 'https://cdn.bootcss.com/fancybox/3.5.7/jquery.fancybox.min.css'
  chart: 'https://cdn.bootcss.com/Chart.js/2.8.0-rc.1/Chart.min.css'

baidu_push: true #baidu push 百度统计标志位

reward: #reward 奖励二维码
  weixin: 'images/weixin.png' #微信
  zhifubao: 'images/zhifubao.png' #知乎

service_worker: #service worker 配合pjax
  open: false #开启sw
